version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: authserviceSistemaBancario_postgres
    restart: always
    environment:
      POSTGRES_DB: DBSistemaBancario
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
     - "5436:5432"
    volumes:
      - postgres_data_01:/var/lib/postgresql/data

volumes:
  postgres_data_01:
